# TensorFlow

In [2]:
import tensorflow as tf

2023-10-31 11:11:29.884925: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-31 11:11:30.406874: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-31 11:11:30.409078: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-31 11:11:32.751863: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [3]:
# scalar creation
scalar = tf.constant(6)

print(f'scalar = {scalar}\ndim = {scalar.ndim}')

scalar = 6
dim = 0


In [4]:
# vector creation
vector = tf.constant([5, 7])

print(f'vector = {vector}\ndim = {vector.ndim}')

vector = [5 7]
dim = 1


In [5]:
# matrix creation
matrix = tf.constant([
    [7, 5, 3],
    [-2, 4, 1],
    [0, 9, 2]
])

print(f'matrix = {matrix}\ndim = {matrix.ndim}')

matrix = [[ 7  5  3]
 [-2  4  1]
 [ 0  9  2]]
dim = 2


In [6]:
# tensor creation
tensor_rank3 = tf.constant([
    [[1, 2, 5], [3, 4, 7]],
    [[1, 2, 5], [3, 4, 7]],
    [[1, 2, 5], [3, 4, 7]],
    [[1, 2, 5], [3, 4, 7]]
])

print(f'tensor = {tensor_rank3}\ndim = {tensor_rank3.ndim}')

tensor = [[[1 2 5]
  [3 4 7]]

 [[1 2 5]
  [3 4 7]]

 [[1 2 5]
  [3 4 7]]

 [[1 2 5]
  [3 4 7]]]
dim = 3


In [7]:
# controling dtype

# float 16
tensor_float16 = tf.constant([2, 4, -1], dtype=tf.float16)

# float 32
tensor_float32 = tf.constant([2, 4, -1], dtype=tf.float32)

# int 32
tensor_int32 = tf.constant([2, 4, -1], dtype=tf.int32)

tensor_float16, tensor_float32, tensor_int32



(<tf.Tensor: shape=(3,), dtype=float16, numpy=array([ 2.,  4., -1.], dtype=float16)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 2.,  4., -1.], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2,  4, -1], dtype=int32)>)

In [8]:
# Variable Tensors
var_tensor = tf.Variable([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

var_tensor

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [9]:
# changing the values of the variable tensor
var_tensor[0].assign([11, 12, 13])
var_tensor

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[11, 12, 13],
       [ 4,  5,  6],
       [ 7,  8,  9]], dtype=int32)>

In [11]:
# random tensors

rand_tensor = tf.random.Generator.from_seed(42)
rand_tensor = rand_tensor.normal(shape=(3, 2, 4))

rand_tensor


<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646]],

       [[-0.7535805 , -0.57166284,  0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ]],

       [[ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
        [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 ]]],
      dtype=float32)>

In [12]:
# shuffle
not_shuffled = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

shuffled = tf.random.shuffle(not_shuffled, seed=42)
shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]], dtype=int32)>

In [13]:
# zeros and ones tensors

zeros_tensor = tf.zeros(shape=(5,4))
ones_tensor = tf.ones(shape=(1, 3))

zeros_tensor, ones_tensor

(<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 1., 1.]], dtype=float32)>)

In [16]:
# converting numpy arrays in to TensorFlow tensors
import numpy as np

np_array = np.array([1, 2, 3])
tf_tensor = tf.constant(np_array, shape=[3])

np_array, tf_tensor

(array([1, 2, 3]),
 <tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>)